### ISSUE TITLE
Allow non literal integers to be used as a task priority

### ISSUE THREAD

**Issue by kareled** [rtic-rs/rtic#1001]
Hello,

I'm attempting to get our application task priorities more under control and neither using enum type mapped to u8 nor u8 constants is working as a value to specify task priority. I always get an error that task macro requires integral literal and nothing more.

```
#[repr(u8)]
pub enum TaskPrio {
  Low = 1,
  Middle = 2,
  High = 3,
  Critical = 4,
[...]
  #[task(priority = TaskPrio::Low ....)
```
or
```
  const LOW : u8 = 1;
  const MIDDLE : u8 = 2;
  const HIGH : u8 = 3;
  const CRITICAL : u8 = 4;
[...]
  #[task(priority = LOW ....)
```
It would be great to have support for at least constants here if not enum type.

Tanks for considering that!
Karel

**Comment by perlindgren** [comment]
Hi Karel

Thanks for your suggestion.

The implementation of RTIC is based on the Rust proc-macros, essentially reading/processing/writing the underlying token stream. Currently the priority field is assuming a literal, which value is used in the computation of resource ceilings for the scheduler at compile time. I'm not sure if it would be possible at compile time resolve structured data.

As an aside:

We are in parallel to the current RTIC codebase (which is a "mono-repo"/"monolithic code base") looking into a modular implementation following the idea of multi-pass compilation. In essence a "pass" will take a "model" as input and produce a new "model" as output in a "lowering" stepwise towards more primitive models, where the final pass generates the executable binary.

Passes can be combined into a distribution, providing the user facing API for building applications.

This work is currently only a research prototype, but it shows the flexibility of the modular approach (experimental targets include both single and multi-core targets and demonstrates the capability to introduce extensions to the (current) RTIC v1 model).

As an example we introduced a "deadline" pass, which turns deadlines into static priorities in a monotonic manner. In context of (hard) real-time systems, this allows the requirements for the scheduler to be specified, and a "ground truth" to for static analysis (providing scheduling guarantees).

As an extension to the "deadline" pass, mixed requirements could be supported, (e.g., hard deadlines regarding I/O operations and relative priorities for best effort scheduling of "services"). This might be done by means of grouping the available hardware priorities such that a subset is dedicated tasks with hard deadlines, while relative priorities would be used by remaining priorities. In this way we could support criticality similar to your example as an edge case.

One can argue that a majority of all embedded systems are indeed mixed critical by nature. This comes from the insight that correct operation of the underlying hardware implies hard real-time requirements, while the "services" implemented by the system typically have no strict timing requirements (however, the overall quality of the system's services might benefit from relative priorities).

E.g., to correctly handle peripheral(s), the corresponding task(s) need to handle the hardware peripheral(s) meeting the requirements of interrupt inter-arrivals (which can be computed from data rate/buffer size(s) etc.). The tasks to parse/process the data can be either hard- or soft real-time (depending on the application requirements). Tasks for logging/statistics, configuration, etc., have typically even lower urgency.

The modular approach allows to express custom passes, extending RTIC in various ways. If the set of passes provided by a distribution lacks needed functionality,  user defined distributions is possible - composing ready made passes with additional user defined "custom" passes in a modular manner.

A huge upside of the modular approach is that syntax extensions (as the one you describe) can be prototyped without forking the RTIC code base. Custom passes (and example distributions) can be published by third party. If a pass/or set of passes proves to be useful in a broader context, they can later be included and maintained by the core team.

In this way we hope to lower the instep for third party contributions, and at the same time improve on flexibility.

A first publication on the subject:

https://ieeexplore.ieee.org/document/10752441


Best regards
  Per

**Comment by perlindgren** [comment]
In particular:
`rtic-macros`, provides the parser:

it looks something like this:

```rust
"priority" => {
                    if priority.is_some() {
                        return Err(parse::Error::new(
                            ident.span(),
                            "argument appears more than once",
                        ));
                    }

                    // #lit
                    let lit: LitInt = input.parse()?;

                    if !lit.suffix().is_empty() {
                        return Err(parse::Error::new(
                            lit.span(),
                            "this literal must be unsuffixed",
                        ));
                    }

                    let value = lit.base10_parse::<u8>().ok();
                    if value.is_none() {
                        return Err(parse::Error::new(
                            lit.span(),
                            "this literal must be in the range 0...255",
                        ));
                    }

                    prio_span = Some(lit.span());
                    priority = Some(value.unwrap());
                }
 ```
Important here is that `priority` (at this point) is declared as an `Option<u8>`, so the literal is parsed into a `u8`.

So the question here is how to turn structured data (even a named const) into a value  at compile time (or rather at proc-macro run-time). I don't think that's doable, but there might be some trick possible, not sure.

**Comment by perlindgren** [comment]
We close this for now as not planned as a fix, but feel free to reopen if alternative solution can be foreseen.
