### ISSUE TITLE
Add API to check software queue fill level

### ISSUE THREAD

**Issue by bradleyharden** [rtic-rs/rtic#428]
It would be nice if there were a way to check the fill level of a software queue. Currently, you can only tell if the queue is full or not full. And even then, you have to try pushing to the queue to do so. Maybe something like `task::queue_len()` and `task::queue_capacity()`?

**Comment by jamesmunns** [comment]
It would also be nice to be able to see the "max depth" ever reached during operation, to help figure out the correct amount necessary in practice.

**Comment by korken89** [comment]
This is no longer part of the API in V2, the external queues can have this implemented outside of RTIC :)
