### ISSUE TITLE
Allow Shared and Local to be public

### ISSUE THREAD

**Issue by David-OConnor** [rtic-rs/rtic#648]
So you can move init code out of the file containing the `RTIC::app`. An attempt to delegate inside `init`, for example, leads to this error:

```rust
1
error: this item must have inherited / private visibility
```

Then in the fn that does the init:
```rust
22  |     app::{Shared, Local, Monotomic},
    |           ^^^^^^ private struct
```

on Shared and Local. Without making them public, I'm not sure how you'd return them from a fn outside the app module.

With this combined with Tasks (eg ISRs) being in the RTIC mod, I'm not sure how to scale RTIC to complex programs without creating huge files. Are there any OSS examples of RTIC being used in a complex app? Thank you.

**Comment by perlindgren** [comment]
Thanks we will have a look.

/Per

**Comment by David-OConnor** [comment]
Btw, then you could use something like this in the RTIC app module macro:

```rust
  #[init]
    fn init(cx: init::Context) -> (Shared, Local, init::Monotonics) {
        startup::init(&cx.core)
    }
```

**Comment by korken89** [comment]
This is now implemented
