### ISSUE TITLE
Spi working in the init function but not within a software defined task

### ISSUE THREAD

**Issue by seanybaggins** [rtic-rs/rtic#707]
I can see the spi is working correctly using a logic analyzer when a spi.write is called within the rtic init function, when I call spi.write within a software task I end up hanging within the spi.write call.

I am using stm32hal2 as my hal. 
**Initialization**
```rust
        let cs = Pin::new(Port::G, 12, PinMode::Output);
        let _sck = Pin::new(Port::C, 10, PinMode::Alt(6));
        let _miso = Pin::new(Port::C, 11, PinMode::Alt(6));
        let _mosi = Pin::new(Port::C, 12, PinMode::Alt(6));

        let mode = SpiMode {
            polarity: SpiPolarity::IdleLow,
            phase: SpiPhase::CaptureOnFirstTransition,
        };
        let spi_config = SpiConfig {
            mode,
            ..Default::default()
        };

        // spi_clock_frequency = 80MHz / BaudRate::<divisor>
        let spi = Spi::new(reg, spi_config, BaudRate::Div32);
```

**Here is where execution hangs**
```rust
// In spi.rs line 557
while !self.regs.sr.read().rxne().bit_is_set() {}
```

Any thoughts or workarounds to getting a spi.write call to work within a software task?
See also https://github.com/David-OConnor/stm32-hal/issues/81

**Comment by Yandrik** [comment]
seems HAL-side (https://github.com/David-OConnor/stm32-hal/issues/81) as far as I can tell

**Comment by seanybaggins** [comment]
Agreed. It looks like there is a blocking read within the write call.

**Comment by Yandrik** [comment]
Could you give me the software task's code that blocks for you? Maybe I can figure out why that is

**Comment by seanybaggins** [comment]
Sorry I can't share more.

**Comment by Yandrik** [comment]
Would it be possible to create a minimum working example? Just an init with the SPI code that executes, and a task that has the SPI code and doesn't execute. Without any code I don't think you'll get any help, unfortunately, as I can't repro the error

**Comment by korken89** [comment]
Hi, please share av example that we can use for debugging the issue.
Without it it'll be very difficult to help :/

**Comment by korken89** [comment]
If an example can be provided, feel free to reopen this.
