### ISSUE TITLE
Whacky behavior with `rtic_monotonics::rp2040::Timer`

### ISSUE THREAD

**Issue by DusterTheFirst** [rtic-rs/rtic#715]
This issue occurs on the latest (as of this issue) master commit of rtic-v2

When using the `rtic_monotonics::rp2040::Timer` monotonic timer implementation on a raspberry pi pico, concurrent timers will appear to "lag", firing delayed and quickly trying to catch up. This behavior can be seen in the two videos below.  Swapping the timer implementation for `rtic_monotonics::systick::Systick` (also while only having one of the cargo features on at a time) will produce the expected, non-"laggy" output.

<details>
<summary>Video with <code>Systick</code> timer (expected result)</summary>

https://user-images.githubusercontent.com/14093962/227809521-a755ec82-a1e9-4cf4-8ab6-1c75ed10fc96.MOV

</details>

<details>
<summary>Video with <code>rp2040</code> timer (odd behavior)</summary>

https://user-images.githubusercontent.com/14093962/227809543-8bd6e48e-1baf-42e7-9657-bd748fea8f3a.MOV

</details>
(The videos are running code with 2 concurrent tasks, with one of them using futures_util's join) the source is not able to be published at this time. 

I have not looked deeply into the code behind the rp2040 timer, but if I were to guess at what is happening, it looks like the timer interrupt (alarm) is being set for the longest delay in the future, rather than the shortest. As short delays will seem to be blocked on longer ones that are happening concurrently. This happens with multiple tasks with different priorities, or one task and `futures_util::future::join`.

**Comment by DusterTheFirst** [comment]
I have created a minimal reproduction of the bug, which you can find here:

https://github.com/DusterTheFirst/pico-things/blob/7666ad5cf011400a034bbea10990545a89ecb30d/projects/pico-rtic-timer-2040-repr/src/main.rs#L89-L128

<details>
<summary>Photo of the output with <code>Systick</code> timer (expected result)</summary>

![image](https://user-images.githubusercontent.com/14093962/228637281-b215eba0-393c-4de0-9ab4-5a6c14bc132c.png)

</details>

<details>
<summary>Photo of the output with <code>rp2040</code> timer (odd behavior)</summary>

![image](https://user-images.githubusercontent.com/14093962/228637351-66026e04-99d7-4f97-b2e1-a4028ad82834.png)

</details>

You can see in the above images, looking at the timestamp in the defmt logs, that in the rp2040 example the second and third "One Second" messages are delayed until the firing of the "Three Seconds" message. This can be confirmed in real-life, watching the logs become more jumpy. This is *not* a problem with the timestamps.

**Comment by datdenkikniet** [comment]
The link you posted doesn't work :(

**Comment by DusterTheFirst** [comment]
@datdenkikniet Oops, it looks like that repository was private. I have made it public.

**Comment by korken89** [comment]
Thanks for reporting! I'll reproduce and fix it

**Comment by korken89** [comment]
There is a fix PR up! Thank to @datdenkikniet for debugging!
