### ISSUE TITLE
`LinkedList` is duplicated

### ISSUE THREAD

**Issue by datdenkikniet** [rtic-rs/rtic#731]
There are two `struct LinkedList` that look verrry similar. One is in  [`rtic-common`](https://github.com/rtic-rs/rtic/blob/master/rtic-common/src/wait_queue.rs#L19) and the other is in [`rtic-time`](https://github.com/rtic-rs/rtic/blob/master/rtic-time/src/linked_list.rs#L13).

Perhaps it would be wise to introduce the change made to `rtic-time` to the `LinkedList` in `rtic-common` and re-use `rtic_common::LinkedList` in `rtic-time`, assuming that they serve the same purpose :)

**Comment by korken89** [comment]
Hi,

They are currently separated as they are 2 different kinds of linked lists.
One is doubly linked and the other is singly linked.

It would however make sense to move the one in `rtic-time` to `rtic-common` and rename the 2 lists to show their differences and have both at a single location.

**Comment by datdenkikniet** [comment]
Ah, oops.

We can start by renaming the Doubly linked list, and go from there!

**Comment by korken89** [comment]
Sounds good!
