### ISSUE TITLE
Removing `nop` from `rtic::export`

### ISSUE THREAD

**Issue by romancardenas** [rtic-rs/rtic#747]
As discussed in #733, re-exporting `nop` in `rtic::export` may be unnecessary, and something like `continue` would do the trick in most cases. Personally, I'd keep the *mandatory* elements of `rtic::export` to the minimum. If anyone needs by chance the `cortex_m::nop` instruction, I'd say that they use it directly from the `cortex-m` crate instead of RTIC's re-export.

**Comment by korken89** [comment]
This sounds good to me. It's a remnant from when loop optimization was broken I'm the compiler.
