### ISSUE TITLE
stm32-metapac and stm32h7 `device.x` collision

### ISSUE THREAD

**Issue by diggit** [rtic-rs/rtic#804]
I am trying to create simple LED blinking app for STM32H730 with recently introduced STM32 monotonics.
They pull in stm32-metapac from embassy. I am also using stm32h7xx-hal (embassy HAL is not so feature rich). Both have their own - incompatible device.x linker files.
By some coincidence, wrong one is being picked by linker, causing:
```
  = note: rust-lld: error: undefined symbol: WWDG1
          >>> referenced by minimal.969bcc94cb32c96a-cgu.0
          >>>               /home/xorly/devel/rust-emb-test/target/thumbv7em-none-eabihf/debug/deps/minimal-2e92aa738f249d54.minimal.969bcc94cb32c96a-cgu.0.rcgu.o:(__INTERRUPTS)
          
          rust-lld: error: undefined symbol: PVD_PVM
          >>> referenced by minimal.969bcc94cb32c96a-cgu.0
          >>>               /home/xorly/devel/rust-emb-test/target/thumbv7em-none-eabihf/debug/deps/minimal-2e92aa738f249d54.minimal.969bcc94cb32c96a-cgu.0.rcgu.o:(__INTERRUPTS)
          
          rust-lld: error: undefined symbol: RTC_TAMP_STAMP_CSS_LSE
          >>> referenced by minimal.969bcc94cb32c96a-cgu.0
          >>>               /home/xorly/devel/rust-emb-test/target/thumbv7em-none-eabihf/debug/deps/minimal-2e92aa738f249d54.minimal.969bcc94cb32c96a-cgu.0.rcgu.o:(__INTERRUPTS)
          ...
```
stm32h7xx-hal device.x:
```
PROVIDE(WWDG1 = DefaultHandler);
PROVIDE(PVD_PVM = DefaultHandler);
PROVIDE(RTC_TAMP_STAMP_CSS_LSE = DefaultHandler);
...
```

stm32-metapac device.x:
```
PROVIDE(WWDG = DefaultHandler);
PROVIDE(PVD_AVD = DefaultHandler);
PROVIDE(TAMP_STAMP = DefaultHandler);
...
```

my project https://gitlab.com/xorly/rust-emb-test
when building, apply fix described in #803

**Comment by AfoHT** [comment]
Does the latest v14 `stm32-metapac` fix this issue? https://github.com/embassy-rs/stm32-data/commit/4af533d90e20705794e507c8ad09c32ebbb76334

It seems to be an issue in between these two HALs. I will close this, but if you feel this is still valid and RTIC related please reopen!
