### ISSUE TITLE
"Cannot compile. No backend feature selected." error when running the examples

### ISSUE THREAD

**Issue by dzamlo** [rtic-rs/rtic#840]
I followed the book and when I reached the [examples chapters](https://rtic.rs/2/book/en/by-example.html) I encountered the following error which come from the end of `rtic-macros/src/lib.rs`:
Cannot compile. No backend feature selected

I was able to make it compile with the following command:
```
cargo run -F thumbv7-backend --target thumbv7m-none-eabi --example locals
```

I don't know if this is the correct way, and if it is, it should be documented in the book.

(Thanks for the work on RTIC. I really like what I see for the moment)

**Comment by AfoHT** [comment]
This should have been resolved in #912 :) Thank you for reporting and happy hacking!
