### ISSUE TITLE
Docs: Examples are broken and not showing

### ISSUE THREAD

**Issue by liamkinne** [rtic-rs/rtic#911]
![Screenshot 2024-03-27 at 11 06 36](https://github.com/rtic-rs/rtic/assets/10735142/45064b7f-da82-4909-b8a2-289db12abfb0)

On this page and a few others: https://rtic.rs/2/book/en/by-example/resources.html

**Comment by perlindgren** [comment]
Good catch. Thanks for the notification.

**Comment by andresv** [comment]
Could you check why it is broken. I would like to demonstrate RTIC in a company show and tell event and showing good docs with examples would be really beneficial.

**Comment by andresv** [comment]
This seems to fix it: https://github.com/rtic-rs/rtic/pull/912.
