### ISSUE TITLE
rtic-monotonics v2.0.2 not compiling

### ISSUE THREAD

**Issue by MikeGstefan** [rtic-rs/rtic#962]
rtic-monotonics v2.0.2 fails to compile with this error: 
` error[E0599]: no method named `fetch_add` found for struct `portable_atomic::AtomicU32` in the current scope `
at rtic-monotonics-2.0.2\src\systick.rs:106:25 and rtic-monotonics-2.0.2\src\systick.rs:126:25

This project has the following config: 
` 
  [build]
  target = "thumbv6m-none-eabi"
  
  [unstable]
  build-std = ["core"]
`

**Comment by korken89** [comment]
Hi @MikeGstefan 

Have you enabled the feature on `portable-atomic` to emulate CAS instructions for `thumbv6`?

**Comment by optlink** [comment]
I just ran into this. I was able to hack around it by adding `portable-atomic` to my project and enabling `critical-section` since `rtic-monotonics` provides no way to enable this feature.

**Comment by robamu** [comment]
I ran into this as well. Might be useful to add some docs for this?

**Comment by robamu** [comment]
See https://github.com/rtic-rs/rtic/pull/977
